src/Entity/Director.php
<?php

namespace App\Entity;

use App\Repository\DirectorRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: DirectorRepository::class)]
// #[ORM\Table(indexes: ['name' => 'search', 'fields' => ['firstname', 'lastname']])] // pas sur
#[ORM\Index(fields: ['firstname', 'lastname'])]
class Director
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $firstname = null;

    #[ORM\Column(length: 100)]
    private ?string $lastname = null;

    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $active = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFullname(): ?string
    {
        return $this->firstname . ' ' . $this->lastname;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function isActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(?bool $active): self
    {
        $this->active = $active;

        return $this;
    }
}

src/Entity/Serie.php
<?php

namespace App\Entity;

use App\Repository\SerieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: SerieRepository::class)]
class Serie
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    #[Assert\NotBlank]
    #[Assert\Length(max: 100)]
    private ?string $title = null;

    #[ORM\Column(nullable: true, options: ['default'=>1])]
    private ?int $season = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Assert\NotBlank]
    private ?\DateTimeInterface $airingDate = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $poster = null;

    #[ORM\OneToMany(mappedBy: 'serie', targetEntity: Note::class, orphanRemoval: true)]
    private Collection $notes;

    #[ORM\ManyToOne]
    private ?Director $director = null;

    public function __construct()
    {
        $this->notes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSeason(): ?int
    {
        return $this->season;
    }

    public function setSeason(int $season): self
    {
        $this->season = $season;

        return $this;
    }

    public function getAiringDate(): ?\DateTimeInterface
    {
        return $this->airingDate;
    }

    public function setAiringDate(?\DateTimeInterface $airingDate): self
    {
        $this->airingDate = $airingDate;

        return $this;
    }

    public function getPoster(): ?string
    {
        return $this->poster;
    }

    public function setPoster(?string $poster): self
    {
        $this->poster = $poster;

        return $this;
    }

    /**
     * @return Collection<int, Note>
     */
    public function getNotes(): Collection
    {
        return $this->notes;
    }

    public function getAverage(): ?float
    {
        // $sum = $this->getNotes()->reduce( fn(int $acc, Note $note) => $acc + $note->getValue(), 0 );

        /* $sum = $this->getNotes()->reduce( function(int $acc, Note $note) {
            return $acc + $note->getValue();
        }, 0);*/

        if( !$this->getNotes()->isEmpty() ) {

            $sum = array_reduce($this->getNotes()->toArray(), function (int $acc, Note $note) {
                return $acc + $note->getValue();
            }, 0);

            return round($sum / $this->getNotes()->count(), 2);
        }

        return null;
    }

    public function addNote(Note $note): self
    {
        if (!$this->notes->contains($note)) {
            $this->notes->add($note);
            $note->setSerie($this);
        }

        return $this;
    }

    public function removeNote(Note $note): self
    {
        if ($this->notes->removeElement($note)) {
            // set the owning side to null (unless already changed)
            if ($note->getSerie() === $this) {
                $note->setSerie(null);
            }
        }

        return $this;
    }

    public function getDirector(): ?Director
    {
        return $this->director;
    }

    public function setDirector(?Director $director): self
    {
        $this->director = $director;

        return $this;
    }
}

src/Form/SerieType.php
<?php

namespace App\Form;

use App\Entity\Director;
use App\Entity\Serie;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SerieType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class)
            ->add('director', EntityType::class, [
                'class' => Director::class,
                'choice_label' => function(Director $director) {
                    return $director->getFullname();
                },
                'placeholder' => 'Choice a director',
                'query_builder' => function(EntityRepository $repository) {
                    return $repository->createQueryBuilder('d')
                        ->where('d.active = :active')
                        ->setParameter('active', true);
                }
            ])
            ->add('season', IntegerType::class, [
                'help' => 'Indiquer le nombre de saison de votre série'
            ])
            ->add('airingDate', DateType::class, [
                'widget' => 'single_text'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Serie::class,
            'required' => false
        ]);
    }
}

src/Controller/SerieController.php
<?php

namespace App\Controller;

use App\Entity\Serie;
use App\Form\SerieType;
use App\Repository\SerieRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/serie', name: 'serie_', requirements: ['id' => '\d+'])]
class SerieController extends AbstractController
{
    /*private $serieRepository;

    public function __construct(SerieRepository $serieRepository)
    {
        $this->serieRepository = $serieRepository;
    }*/

    public function __construct(private SerieRepository $serieRepository) { }

    #[Route('', name: 'index')]
    public function index(): Response
    {
        // $series = $this->serieRepository->findAll();
        $series = $this->serieRepository->findAllWithNotes();

        return $this->render('serie/index.html.twig', [
            'series' => $series
        ]);
    }

    #[Route('/add', name: 'add')]
    public function add(Request $request): Response
    {
        $serie = new Serie();
        $form = $this->createForm(SerieType::class, $serie);

        $form->handleRequest($request);
        if( $form->isSubmitted() && $form->isValid() ) {
            $this->serieRepository->save($serie, true);

            $this->addFlash('success', 'La série a bien été enregistrée');
            return $this->redirectToRoute('serie_index');
        }

        return $this->render('serie/edit.html.twig', [
            'formView' => $form
        ]);
    }

    #[Route('/{id}/detail', name: 'detail')]
    public function detail(Serie $serie): Response
    {
        // ParamConverter => transforme la clé transmis dans l'url en une instance
        // de l'entité demandé

        return $this->render('serie/detail.html.twig', [
            'serie' => $serie
        ]);
    }

    #[Route('/{id}/detail/note', name: 'detail_notes')]
    public function detailNotes(int $id): Response
    {
        $serie = $this->serieRepository->findOneWithNotes($id);

        if(!$serie) {
            throw $this->createNotFoundException();
        }

        return $this->render('serie/detail_notes.html.twig', [
            'serie' => $serie
        ]);
    }
}

templates/serie/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ serie.title }}{% endblock %}

{% block body %}
    <h2>{{ serie.title }}</h2>

    <div class="mb-3">
        <a href="{{ path('serie_index') }}" class="btn btn-sm btn-outline-dark">Revenir à la liste</a>
    </div>

    {% if serie.poster %}
        <figure class="figure">
            <img src="{{ asset('poster/' ~ serie.poster) }}"
                 class="figure-img img-fluid rounded" alt="" />
        </figure>
    {% endif %}

    <dl class="row small">
        <dt class="col-2">Nombre de saison</dt>
        <dd class="col-10">{{ serie.season }}</dd>
        <dt class="col-2">1er Diffusion</dt>
        <dd class="col-10">{{ serie.airingDate | format_date('full') }}</dd>
    </dl>
{% endblock %}

templates/serie/detail_notes.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ serie.title }}{% endblock %}

{% block body %}
    <h2>{{ serie.title }}</h2>

    <div class="mb-3">
        <a href="{{ path('serie_index') }}" class="btn btn-sm btn-outline-dark">Revenir à la liste</a>
    </div>

    {% if serie.poster %}
        <figure class="figure">
            <img src="{{ asset('poster/' ~ serie.poster) }}"
                 class="figure-img img-fluid rounded" alt="" />
        </figure>
    {% endif %}

    <dl class="row small">
        <dt class="col-2">Nombre de saison</dt>
        <dd class="col-10">{{ serie.season }}</dd>
        <dt class="col-2">1er Diffusion</dt>
        <dd class="col-10">{{ serie.airingDate | format_date('full') }}</dd>
        <dt class="col-2">Moyenne</dt>
        <dd class="col-10">
            {{ not serie.average ? "-" : serie.average | format_number ~ " / 10" }}
        </dd>
    </dl>
{% endblock %}

templates/serie/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editer une série{% endblock %}

{% block body %}
    <h2>Editer des séries</h2>

    <div class="mb-3">
        <a href="{{ path('serie_index') }}" class="btn btn-sm btn-outline-dark">Revenir à la liste</a>
    </div>

    {# {{ form(formView) }} #}

    {{ form_start(formView) }}

    {# {{ form_row(formView.title) }}

    <div>
        {{ form_label(formView.season) }}
        {{ form_errors(formView.season) }}
        <br />
        {{ form_widget(formView.season) }}
        {{ form_help(formView.season) }}
    </div>  #}

    {{ form_rest(formView) }}

    <button class="btn btn-primary">Enregister la série</button>
    {# <input type="submit" />

    <button type="button">cancel</button>
    <input type="button" /> #}

    {{ form_end(formView) }}

{% endblock %}

templates/serie/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des séries{% endblock %}

{% block body %}
    <h2>Liste des séries</h2>

    <div class="mb-3">
        <a href="{{ path('serie_add') }}" class="btn btn-sm btn-outline-primary">Ajouter une série</a>
    </div>

    <table class="table">
        <thead>
        <tr>
            <th>ID</th>
            <th>Titre</th>
            <th>Nombre de saison</th>
            <th>Date de diffusion</th>
            <th>Réalisateur</th>
            <th>Notes</th>
            <th>Moyenne</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for serie in series %}
            <tr>
                <td>{{ serie.id }}</td>
                <td>{{ serie.title }}</td>
                <td>{{ serie.season }}</td>
                <td>{{ serie.airingDate | format_date }}</td>
                <td>{{ not serie.director ? '-' : serie.director.fullname | capitalize }}</td>
                <td>
                    <ul class="list-unstyled">
                    {% for note in serie.notes %}
                        <li>{{ note.value }} / 10</li>
                    {% else %}
                        <li> - </li>
                    {% endfor %}
                    </ul>
                </td>
                <td>
                    {{ not serie.average ? "-" : serie.average | format_number ~ " / 10" }}

                    {# {% if serie.average is not null %}
                        {{ serie.average | format_number }} / 10
                    {% else %}
                        -
                    {% endif %} #}
                </td>
                <td>
                    <a href="{{ path('serie_detail', {'id': serie.id}) }}">
                        Détail Série</a> -
                    <a href="{{ path('serie_detail_notes', {'id': serie.id}) }}">
                        Détail Série + Notes</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7" class="text-center text-black-50">Aucune série enregistré actuellement</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}